config/routes.rb
Rails.application.routes.draw do

  root 'restaurant#index'
  resources :restaurants do
    resources :reviews
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews

  validates_presence_of :name
  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip_code
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :rating,
    presence: true,
    :inclusion => 1..5
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    id = params[:id]
    @restaurant = Restaurant.find(id)
    @reviews = Review.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
    render :new
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zip_code, :desciption)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant_id = @restaurant.id
    if @review.save
      redirect_to @restaurant, notice: "Review sucessfully created."
    else
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:rating, :body, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <h1> goodEats</h1>
  </div>
  <div class="notice">
    <%= notice %>
  </div>

  <div class="button">
    <%= link_to("Post a Restaurant", new_restaurant_path)  %>
    <%= link_to("Back to Home", restaurants_path)  %>
  </div>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
<% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this question from being saved:</h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_area :zip_code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <div class="restaurant">
    <a href="<%= restaurant_path(restaurant.id) %>">
      <h2><%= restaurant.name %> </h2></a>
      <p>city: <%= restaurant.city %></p>
    </a>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<h2> Post a new Restaurant<h2>
  <%= render 'form' %>

app/views/restaurants/show.html.erb
<div class='restaurant'>
  <h1><%= @restaurant.name %></h1>

  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.city %></p>
  <p><%= @restaurant.state %></p>
  <p><%= @restaurant.zip_code %></p>
  <p><%= @restaurant.description %></p>
  <h4>Reviews</h4>
  <% @reviews.each  do |review| %>
    <h5> <%= review.rating %> </h5>
    <p> <%= review.body %></p>
  <% end %>
</div>
<div class="button">
  <%= link_to "Review this Restaurant", new_restaurant_review_path(@restaurant) %>
</div>

app/views/reviews/new.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this question from being saved:</h2>
    <ul>
      <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit "Post" %>
  </div>

<% end %>